Transactions-ADO.NET/Controllers/ClienteController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Transactions_ADO.NET.DAO;
using Transactions_ADO.NET.Models;

namespace Transactions_ADO.NET.Controllers
{
    public class ClienteController : Controller
    {
        private readonly ClienteDAO clienteDAO = new ClienteDAO();
        private readonly DistritoDAO distritoDAO = new DistritoDAO();

        [HttpGet]
        public ActionResult ListarClientes (string eli_cli = "No", int pagina = 0)
        {
            var cantidadTotal = clienteDAO.ListarClientes(eli_cli).Count;
            var cantidadPorPagina = 5;
            var numeroPaginas = (cantidadTotal + cantidadPorPagina - 1) / cantidadPorPagina;

            ViewBag.pagina = pagina;
            ViewBag.numeroPaginas = numeroPaginas;


            var listado = clienteDAO.ListarClientes(eli_cli).Skip(cantidadPorPagina * pagina).Take(cantidadPorPagina);

            return View(listado);
        }

        [HttpGet]
        //Obtener los datos del cliente para grabar
        public ActionResult GrabarClientes ()
        {
            var cliente = new Cliente();

            cliente.fec_nac = new DateTime();
            ViewBag.distritos = new SelectList(distritoDAO.ListadoDistritos(), "cod_dist", "nom_dist");

            return View(cliente);
        }

        [HttpPost]
        public ActionResult GrabarClientes (Cliente cliente)
        {
            var cadena = "";

            try
            {
                //Si el modelo enviado no tiene errores
                if (ModelState.IsValid) cadena = clienteDAO.GrabarCliente(cliente);
            }
            catch (Exception e)
            {
                cadena = "Error al grabar el cliente: " + e.Message;
            }

            ViewBag.mensaje = cadena;
            ViewBag.distritos = new SelectList(distritoDAO.ListadoDistritos(), "cod_dist", "nom_dist");
            return View(cliente);
        }


        public ActionResult DetalleCliente (string id)
        {
            var listado = clienteDAO.ListarClientes("No");

            var cliente = listado.Find(x => x.cod_cli.Equals(id));

            return View(cliente);
        }

        [HttpGet]
        public ActionResult EditarCliente (string id)
        {
            var listado = clienteDAO.ListarClientes("No");

            var cliente = listado.Find(x => x.cod_cli.Equals(id));

            return cliente == null ? View() : View(cliente);
        }

        [HttpPost]
        public ActionResult EditarCliente (Cliente cliente)
        {
            string mensage = string.Empty;

            try
            {
                ViewBag.MENSAJE = ModelState.IsValid ? clienteDAO.ActualizarCliente(cliente) : "ERROR EN LA VALIDACION DE DATOS";
            }
            catch (Exception e)
            {
                ViewBag.MENSAJE = "Error al actualizar el cliente: " + e.Message;
            }

            return View(cliente);
        }

        [HttpGet]
        public ActionResult EliminarCliente (string id)
        {
            var listado = clienteDAO.ListarClientes("No");
            Cliente cliente = listado.Find(x => x.cod_cli.Equals(id));

            return View(cliente);
        }

        [HttpPost]
        public ActionResult EliminarCliente (string id, FormCollection collection)
        {
            ViewBag.MENSAJE = clienteDAO.EliminarCliente(id);
            return View();
        }
    }
}

Transactions-ADO.NET/Controllers/VentasCabController.cs
using System.Linq;
using System.Web.Mvc;
using Transactions_ADO.NET.DAO;
using Transactions_ADO.NET.Models;

namespace Transactions_ADO.NET.Controllers
{
    public class VentasCabController : Controller
    {
        private readonly VentasCabDAO ventasCabDao = new VentasCabDAO();

        [HttpGet]
        public ActionResult ObtenerVentas ()
        {
            var vendedores = ventasCabDao.ObtenerVendedores();
            var clientes = ventasCabDao.ObtenerClientes();

            var viewModel = new FiltroVentaViewModel
            {
                Vendedores = vendedores.Select(v => new SelectListItem
                {
                    Value = v.CodVen.ToString(),
                    Text = v.NomVen
                }).ToList(),
                Clientes = clientes.Select(c => new SelectListItem
                {
                    Value = c.cod_cli,
                    Text = c.cod_cli
                }).ToList()
            };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Filtrar (FiltroVenta filtros)
        {
            var ventas = ventasCabDao.ListarVentasCabs(filtros);
            return PartialView("_ResultadosParciales", ventas);
        }
    }
}

Transactions-ADO.NET/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
    <div class="container">
        @Html.ActionLink("Ventas App", "ListarClientes", "Cliente", new { @class = "navbar-brand" })
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li>@Html.ActionLink("Cliente", "ListarClientes", "Cliente", new { area = "" }, new { @class = "nav-link" })</li>
                <li>@Html.ActionLink("Ventas Por Vendedor", "ObtenerVentas", "VentasCab", new { area = "" }, new { @class = "nav-link" })</li>
            </ul>
        </div>
    </div>
</nav>
<div class="container body-content">
    @RenderBody()
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
    </footer>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.unobtrusive-ajax/3.2.6/jquery.unobtrusive-ajax.min.js"></script>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", false)
</body>
</html>