DropdownsAnidados/Models/Chofer.cs
namespace DropdownsAnidados.Models
{
    public class Chofer
    {
        public string CodChofer { get; set; }
        public string? NombreChofer { get; set; }
    }
}

DropdownsAnidados/Models/Ruta.cs
namespace DropdownsAnidados.Models
{
    public class Ruta
    {
        public string CodRuta { get; set; }
        public string? Destino { get; set; }
    }
}

DropdownsAnidados/Models/Viajes.cs
namespace DropdownsAnidados.Models
{
    public class Viajes
    {
        public string? Hora_Salida { get; set; }
    }
}

DropdownsAnidados/Models/ViajesRutaViewModel.cs
using System.Collections.Generic;

namespace DropdownsAnidados.Models;

public class ViajesRutaViewModel
{
    public List<Viajes> Viajes { get; set; }
    public List<Ruta> Rutas { get; set; }
    public List<sp_ListarViajes> ListarViajes { get; set; }
    public List<Chofer> Chofers { get; set; }
    public sp_ListarViajes Viaje { get; set; }
}

DropdownsAnidados/Models/sp_ListarViajes.cs
namespace DropdownsAnidados.Models
{
    public class sp_ListarViajes
    {
        public string Cod_Ruta { get; set; }
        public string Cod_Chofer { get; set; }
        public string Nombre_Chofer { get; set; }
        public string Destino { get; set; }
        public string Hora_Salida { get; set; }
        public decimal Costo_Via { get; set; }
        public string Nro_Via { get; set; }
    }
}

DropdownsAnidados/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DropdownsAnidados.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index ()
        {
            return View();
        }

        public ActionResult About ()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact ()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

DropdownsAnidados/Controllers/ListarViajesController.cs
using DropdownsAnidados.DAO;
using DropdownsAnidados.Models;
using System.Linq;
using System.Web.Mvc;

namespace DropdownsAnidados.Controllers;

public class ListarViajesController : Controller
{
    // GET: ListarViajes
    private readonly ViajeDAO viajeDao = new();
    private readonly RutaDAO rutaDao = new();
    private readonly ChoferDAO choferDao = new();
    private readonly sp_Listar_Viajes_DAO sp_Listar_Viajes_DAO = new();

    [HttpGet]
    public ActionResult ListarViajesPersonalizado (string cod_rut = null, string cod_chof = null, string hrs_sal = null)
    {
        var viajes = viajeDao.ListarViajes();
        var rutas = rutaDao.ListarRutas();
        var chofers = choferDao.ListarChofers();
        var sp_viajes = sp_Listar_Viajes_DAO.SP_ListarViajes(cod_rut, cod_chof, hrs_sal);

        var viewModel = new ViajesRutaViewModel
        {
            Viajes = viajes,
            Rutas = rutas,
            Chofers = chofers,
            ListarViajes = sp_viajes
        };

        return View(viewModel);
    }

    [HttpGet]
    public ActionResult EditarViajes (string nroVia)
    {
        var viaje = sp_Listar_Viajes_DAO.SP_ListarViajes().FirstOrDefault(v => v.Nro_Via == nroVia);
        if (viaje == null)
        {
            return HttpNotFound();
        }

        var rutas = rutaDao.ListarRutas();
        var chofers = choferDao.ListarChofers();

        var viewModel = new ViajesRutaViewModel { Viaje = viaje, Rutas = rutas, Chofers = chofers };

        return View(viewModel);
    }

    [HttpPost]
    public ActionResult EditarViajes (ViajesRutaViewModel viewModel)
    {
        if (ModelState.IsValid)
        {
            sp_Listar_Viajes_DAO.SP_Editar_Viajes(
                    viewModel.Viaje.Nro_Via,
                    viewModel.Viaje.Cod_Ruta,
                    viewModel.Viaje.Cod_Chofer,
                    viewModel.Viaje.Hora_Salida,
                    viewModel.Viaje.Costo_Via
                );
            return RedirectToAction("ListarViajesPersonalizado");
        }

        viewModel.Rutas = rutaDao.ListarRutas();
        viewModel.Chofers = choferDao.ListarChofers();
        return View(viewModel);
    }

    [HttpGet]
    public ActionResult DetallesViaje (string nroVia)
    {
        var viaje = sp_Listar_Viajes_DAO.SP_ListarViajes().FirstOrDefault(v => v.Nro_Via == nroVia);
        if (viaje == null)
        {
            return HttpNotFound();
        }

        var rutas = rutaDao.ListarRutas();
        var chofers = choferDao.ListarChofers();

        var viewModel = new ViajesRutaViewModel { Viaje = viaje, Rutas = rutas, Chofers = chofers };

        return View(viewModel);
    }

    [HttpGet]
    public ActionResult EliminarViaje (string nroVia)
    {
        sp_Listar_Viajes_DAO.SP_Eliminar_Viaje(nroVia);
        return RedirectToAction("ListarViajesPersonalizado");
    }


}

DropdownsAnidados/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

DropdownsAnidados/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

DropdownsAnidados/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

DropdownsAnidados/Views/ListarViajes/DetallesViaje.cshtml
@model DropdownsAnidados.Models.ViajesRutaViewModel

@{
    ViewBag.Title = "DetallesViaje";
}

<h2>Detalles del Viaje</h2>

<div class="form-group">
    @Html.LabelFor(model => model.Viaje.Nro_Via)
    <p class="form-control-static">@Model.Viaje.Nro_Via</p>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Viaje.Cod_Ruta)
    <p class="form-control-static">@Model.Viaje.Cod_Ruta</p>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Viaje.Cod_Chofer)
    <p class="form-control-static">@Model.Viaje.Cod_Chofer</p>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Viaje.Hora_Salida)
    <p class="form-control-static">@Model.Viaje.Hora_Salida</p>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Viaje.Costo_Via)
    <p class="form-control-static">@Model.Viaje.Costo_Via</p>
</div>

@Html.ActionLink("Volver", "ListarViajesPersonalizado", null, new { @class = "btn btn-secondary" })

DropdownsAnidados/Views/ListarViajes/EditarViajes.cshtml
@model DropdownsAnidados.Models.ViajesRutaViewModel

@{
    ViewBag.Title = "Editar Viaje";
}

<h2>Editar Viaje</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Viaje.Nro_Via)

    <div class="form-group">
        @Html.LabelFor(model => model.Viaje.Cod_Ruta)
        @Html.DropDownListFor(model => model.Viaje.Cod_Ruta, new SelectList(Model.Rutas, "CodRuta", "Destino"), "Seleccione una Ruta", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Viaje.Cod_Ruta, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Viaje.Cod_Chofer)
        @Html.DropDownListFor(model => model.Viaje.Cod_Chofer, new SelectList(Model.Chofers, "CodChofer", "NombreChofer"), "Seleccione un Chofer", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Viaje.Cod_Chofer, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Viaje.Hora_Salida)
        @Html.EditorFor(model => model.Viaje.Hora_Salida, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Viaje.Hora_Salida, "", new { @class = "text-danger" })
    </div>

   

    <div class="form-group">
        @Html.LabelFor(model => model.Viaje.Costo_Via)
        @Html.EditorFor(model => model.Viaje.Costo_Via, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Viaje.Costo_Via, "", new { @class = "text-danger" })
    </div>

    <button type="submit" class="btn btn-primary">Guardar</button>
    @Html.ActionLink("Cancelar", "ListarViajesPersonalizado", null, new { @class = "btn btn-secondary" })
}

DropdownsAnidados/Views/ListarViajes/ListarViajesPersonalizado.cshtml
@model DropdownsAnidados.Models.ViajesRutaViewModel

@{
    ViewBag.Title = "ListarViajesPersonalizado";
}

<h2>ListarViajesPersonalizado</h2>

<select id="viajesSelect">
    <option value="">Selecione un Viaje</option>
    @foreach (var viaje in Model.Viajes)
    {
        <option value="@viaje.Hora_Salida">@viaje.Hora_Salida</option>
    }
</select>

<select id="rutasSelect">
    <option value="">Selecione una Ruta</option>
    @foreach (var ruta in Model.Rutas)
    {
        <option value="@ruta.CodRuta">@ruta.Destino</option>
    }
</select>

<select id="chofersSelect">
    <option value="">Seleciona un Chofer</option>
    @foreach (var chofer in Model.Chofers)
    {
        <option value="@chofer.CodChofer">@chofer.NombreChofer</option>
    }
</select>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div id="viajesTableContainer">
    <table class="table table-hover">
        <tr>
            <th>@Html.DisplayNameFor(model => model.ListarViajes.First().Cod_Ruta)</th>
            <th>@Html.DisplayNameFor(model => model.ListarViajes.First().Cod_Chofer)</th>
            <th>@Html.DisplayNameFor(model => model.ListarViajes.First().Nombre_Chofer)</th>
            <th>@Html.DisplayNameFor(model => model.ListarViajes.First().Destino)</th>
            <th>@Html.DisplayNameFor(model => model.ListarViajes.First().Hora_Salida)</th>
            <th>@Html.DisplayNameFor(model => model.ListarViajes.First().Costo_Via)</th>
            <th>@Html.DisplayNameFor(model => model.ListarViajes.First().Nro_Via)</th>
            <th></th>
            <th></th>
        </tr>

        @foreach (var item in Model.ListarViajes)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Cod_Ruta)</td>
                <td>@Html.DisplayFor(modelItem => item.Cod_Chofer)</td>
                <td>@Html.DisplayFor(modelItem => item.Nombre_Chofer)</td>
                <td>@Html.DisplayFor(modelItem => item.Destino)</td>
                <td>@Html.DisplayFor(modelItem => item.Hora_Salida)</td>
                <td>@Html.DisplayFor(modelItem => item.Costo_Via)</td>
                <td>@Html.DisplayFor(modelItem => item.Nro_Via)</td>
                <td>
                    @Html.ActionLink("Edit", "EditarViajes", new { nroVia = item.Nro_Via }, new { @class = "btn btn-outline-primary" })
                    @Html.ActionLink("Details", "DetallesViaje", new { nroVia = item.Nro_Via }, new { @class = "btn btn-outline-secondary" })
                    <button class="btn btn-outline-danger" onclick="confirmarEliminacion('@item.Nro_Via')">Eliminar</button>
                </td>
            </tr>
        }
    </table>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    document.getElementById("viajesSelect").addEventListener("change",
        function() {
            console.log("Viaje Selecionado :" + this.value);
        });
    document.getElementById("rutasSelect").addEventListener("change",
        function() {
            console.log("Codigo de ruta selecinado :" + this.value);
        });

    document.getElementById("chofersSelect").addEventListener("change",
        function() {
            console.log("El id del chofer selecionado : " + this.value);
        });

    $(document).ready(function() {
        $("#viajesSelect, #rutasSelect, #chofersSelect").change(function() {
            var cod_rut = $("#rutasSelect").val();
            var cod_chof = $("#chofersSelect").val();
            var hrs_sal = $("#viajesSelect").val();

            $.ajax({
                url: '@Url.Action("ListarViajesPersonalizado", "ListarViajes")',
                type: "GET",
                data: {
                    cod_rut: cod_rut,
                    cod_chof: cod_chof,
                    hrs_sal: hrs_sal
                },
                success: function(result) {
                    var newTable = $(result).find("#viajesTableContainer").html();
                    $("#viajesTableContainer").html(newTable);
                },
                error: function(xhr, status, error) {
                    console.error("Error en la solicitud AJAX: " + error);
                }
            });
        });
    });

    function confirmarEliminacion(nroVia) {
        Swal.fire({
            title: '¿Estás seguro?',
            text: "¡No podrás revertir esto!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Sí, eliminarlo!'
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = '@Url.Action("EliminarViaje", "ListarViajes")?nroVia=' + nroVia;
            }
        });
    }


</script>

DropdownsAnidados/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Nombre de la aplicación", "ListarViajesPersonalizado", "ListarViajes", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Lista de Viajes Personaliada", "ListarViajesPersonalizado", "ListarViajes", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>